
# Suggested time that the scanning motion should take

duration motion_duration

---
# Results

actionlib_msgs/GoalStatus status

# Suggested deployment poses, from best to worse. Size zero if anything failed.
DeploymentPose[] deployment_poses

---
# Feedback
int8 execution_percent #range [0,100]
