#simplification of http://docs.ros.org/api/moveit_msgs/html/action/ExecuteTrajectory.html

#goal (pose in joint space (name of a pre-recorded pose)
string pose_identifier

---
# result
moveit_msgs/MoveItErrorCodes error_code

---
#feedback. Range is [0,100]
int8 execution_percent
