
# Where to place the dispenser. Ordered from "better" to worse
DeploymentPose[] deployment_poses

---
# Result
moveit_msgs/MoveItErrorCodes error_code

---
# Feedback. Range is [0,100]
int8 execution_percent
