
# Suggested time that the scanning motion should take

duration motion_duration_hint

---
# Results

# If failed, return here the error
moveit_msgs/MoveItErrorCodes error_code

# this is for the coordinator, to be aware of the duration of the scan motion.
# this is useful in order to select the laser scan for the point cloud analysis
duration actual_motion_duration
---
# Feedback
int8 execution_percent #range [0,100]
