
# Suggested time that the scanning motion should take


---
# Results

actionlib_msgs/GoalStatus status

# Suggested deployment poses, from best to worse. Size zero if anything failed.
DeploymentPose[] deployment_poses

---
# Feedback


