Header header                  # the frame the request and response are referenced in
RoutePoint[]  route_points     # proposed route

---

uint32  uid      #uid of the route
bool success     # indicate successful run of service
string message   # informational, e.g. for error messages
