string status

string STEP1  = "Arm in pre-picking Pose, looking for desired position of the marker"
string STEP2  = "Desired features of the marker have been computed"
string STEP3  = "Starting to pick up the dispenser, starting visual control..."
string STEP4  = "Grasping Position is reached, opening fingers..."
string STEP5  = "Dispenser grasped..."
string STEP6  = "Dispenser extracted"
string STEP7  = "Moving in front of deployment position"
string STEP8  = "Arm is in front of the deployment position"
string STEP9  = "Point cloud registered"
string STEP10 = "Correct deployment point computed"
string STEP11 = "Dispenser has been placed, replacing the arm..."
string STEP12 = "Arm is back to park position"
